### ISSUE TITLE
Linux build double-zip problem

### ISSUE THREAD

**Issue by cibikle** [cibikle/LaSSI#143]
The Linux build workflow produces a zipped zip file. That's inconvenient. The upload step automatically zips the artifact and I'm not sure how to prevent that. Why not remove the step that zips the file before upload? Can't! Need that to protect the exec bit. I think.

**Comment by Totengeist** [comment]
I think you need to remove line 46 (`zip LaSSI.zip LaSSI`) and replace line 55 with:

```
        path: ${{ env.Wap_Project_Directory }}/output/LaSSI.zip
```

If you look at your Windows workflow, you're just giving `actions/upload-artifact@v3` the whole output directory, whereas in the Linux workflow, you're giving it the ZIP file. It's taking the input you give it and zipping it. Since you're zipping either way, it should still save the exec bit.
